### ISSUE TITLE
didn't show the complete cycles, but the short ones ( example: a-b-a; c-d-c... )

### ISSUE THREAD

**Issue by Diiiiii-9** [JamesBremner/graphCycler#1]
Hi,
I tried to plot a graph like:
```c
0----1
|    |
|    |
3----2 
```
so I code it like:
```c
cGraph graph;
graph.addEdge("0", "1");
graph.addEdge("1", "2");
graph.addEdge("2", "3");
graph.addEdge("3", "0");
```
I thought it would get a result like:
```C
node 0 linked to 1 3
node 1 linked to 0 2
node 2 linked to 1 3
node 3 linked to 2 0
cycle: 0 1 2 3 0
```
However the result is:
```C
node 0 linked to 1 3
node 1 linked to 0 2
node 2 linked to 1 3
node 3 linked to 2 0
cycle: 0 3 0
cycle: 3 2 3
cycle: 0 1 0
cycle: 2 1 2
```
Do I misunderstand how to use the code you provided?

**Comment by JamesBremner** [comment]
Thank you for your interest in my code.

I haven't looked at this repo for a couple of months.

My "latest and greatest" is at https://github.com/JamesBremner/PathFinder/wiki/Cycles

Here is a screenshot of a run of your test using that code

![image](https://user-images.githubusercontent.com/2046227/227786797-059dbd3a-bd37-41dd-8476-184f0ff5aa83.png)

**Comment by JamesBremner** [comment]
I took a look at this.  The cause is that, by default, the graph is created with undirected edges - which means ever edge can be uses as a cycle of length 2.

**Comment by JamesBremner** [comment]
Problem fixed.

Note that you need to set the graph to directed after construction.

This code:

https://github.com/JamesBremner/graphCycler/blob/1c1b48e8d494434b7b1903ba6f0d9e076409386e/src/main.cpp#L1-L27

Outputs

```
node a linked to b 
node b linked to c
node c linked to d
node d linked to a
cycle: a b c d a
```

----------------------------

For any future work, I would prefer that you use https://github.com/JamesBremner/PathFinder

**Comment by JamesBremner** [comment]
@Diiiiii-9 Hello?  Are you good?

**Comment by Diiiiii-9** [comment]
It works in my own program! Thank you. =)
(Bit of a busy day today. Sorry for the delay in responding.)

**Comment by JamesBremner** [comment]
@Diiiiii-9 I have improved the cycle finding code to handle both directed and undirected graphs.  The new code is in https://github.com/JamesBremner/PathFinder, not in this repository which is now obsolete

https://github.com/JamesBremner/PathFinder/blob/289b6e1695be9cc2d342b0bad4dd720a1ba51e87/src/GraphTheory.cpp#L310-L425
